# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog17', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentmodel',
            old_name='author',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='blogpostmodel',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
